name: Deploy production docs to Azure

on:
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: windows-latest
    name: Build Docs
    steps:
      - name: Install DocFX
        run: choco install docfx --version=2.59.4 -y

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1.8.1

      - name: Build docs with DocFX
        shell: pwsh
        run: |
             $env:GITHUB_ACTIONS='false'
             docfx .\docfx_project\docfx.json

      - name: Upload docs as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: site
          path: docfx_project/_site/

  deploy_docs:
    needs: build_docs
    runs-on: ubuntu-latest
    name: Deploy Docs
    steps:
      - name: Dowload docs build
        uses: actions/download-artifact@v2.0.10
        with:
          name: site
          path: site

      - name: Deploy docs
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_DOCS_PRODUCTION_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./site" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
